import { useState } from 'react'
import { AlertCircle, ArrowDownLeft, ArrowUpRight, CalendarDays, HandCoins, Plus } from 'lucide-react'
import Modal from '../../components/common/Modal'
import PageTitle from '../../components/common/PageTitle'
import ProgressBar from '../../components/common/ProgressBar'
import { useFinance } from '../../context/FinanceContext'
import { formatCurrency } from '../../utils/formatters'

const records={utang:[{name:'Pinjaman keluarga',total:5000000,remaining:2500000,due:'15 Des 2026',monthly:500000}],piutang:[{name:'Dana talangan — Dimas',total:1200000,remaining:800000,due:'20 Agu 2026',monthly:400000}],cicilan:[{name:'Laptop kerja',total:20400000,remaining:11900000,due:'10 tiap bulan',monthly:850000,cash:18000000}]}
export default function DebtsPage(){const[tab,setTab]=useState('utang');const[open,setOpen]=useState(false);const{notify}=useFinance();return <><PageTitle eyebrow="KEWAJIBAN & TAGIHAN" title="Utang & Piutang" subtitle="Ketahui apa yang harus dibayar dan apa yang akan diterima." action={<button className="primary-btn" onClick={()=>setOpen(true)}><Plus/>Tambah data</button>}/><div className="page-tabs"><button className={tab==='utang'?'active':''} onClick={()=>setTab('utang')}>Utang</button><button className={tab==='piutang'?'active':''} onClick={()=>setTab('piutang')}>Piutang</button><button className={tab==='cicilan'?'active':''} onClick={()=>setTab('cicilan')}>Cicilan</button></div><section className="debt-summary"><article><i className="expense"><ArrowUpRight/></i><span>Total sisa utang<strong>{formatCurrency(2500000)}</strong></span></article><article><i className="income"><ArrowDownLeft/></i><span>Piutang belum diterima<strong>{formatCurrency(800000)}</strong></span></article><article><i><HandCoins/></i><span>Kewajiban bulanan<strong>{formatCurrency(1350000)}</strong></span></article></section><div className="debt-list">{records[tab].map(item=><article className="card debt-card" key={item.name}><header><span><strong>{item.name}</strong><small>{tab==='cicilan'?'Cicilan aktif':tab==='utang'?'Utang aktif':'Menunggu pembayaran'}</small></span><em>{tab==='piutang'?'Akan diterima':'Aktif'}</em></header><div className="debt-values"><span>Sisa<strong>{formatCurrency(item.remaining)}</strong></span><span>Jumlah awal<strong>{formatCurrency(item.total)}</strong></span><span>Per bulan<strong>{formatCurrency(item.monthly)}</strong></span></div><ProgressBar value={(item.total-item.remaining)/item.total*100}/><footer><span><CalendarDays/>{item.due}</span>{item.cash&&<span className="cost-note"><AlertCircle/>Biaya tambahan {formatCurrency(item.total-item.cash)}</span>}<button className="secondary-btn">Catat pembayaran</button></footer></article>)}</div><Modal open={open} onClose={()=>setOpen(false)} title={`Tambah ${tab}`}><form className="finance-form" onSubmit={e=>{e.preventDefault();notify('Data berhasil ditambahkan');setOpen(false)}}><div className="form-grid"><label>Nama<input required/></label><label>Jumlah awal<input required type="number" min="1"/></label><label>Jatuh tempo<input type="date"/></label><label>Cicilan per bulan<input type="number" min="0"/></label><label>Bunga (%)<input type="number" min="0" step="0.1"/></label><label>Status<select><option>Aktif</option><option>Lunas</option></select></label></div><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Batal</button><button className="primary-btn">Simpan</button></div></form></Modal></>}
