import { useState } from 'react'
import { Archive, ArrowDownLeft, ArrowRight, ArrowUpRight, Plus, RotateCcw, Scale } from 'lucide-react'
import AccountCard from '../../components/accounts/AccountCard'
import AccountForm from '../../components/forms/AccountForm'
import Modal from '../../components/common/Modal'
import PageTitle from '../../components/common/PageTitle'
import { useFinance } from '../../context/FinanceContext'
import { getPeriodSummary } from '../../utils/analytics'
import { formatCurrency } from '../../utils/formatters'

export default function AccountsPage(){
 const [open,setOpen]=useState(false); const [reconcile,setReconcile]=useState(null); const [deactivating,setDeactivating]=useState(null); const {accounts,transactions,notify,toggleAccountActive}=useFinance(); const activeAccounts=accounts.filter(a=>a.isActive!==false); const inactiveAccounts=accounts.filter(a=>a.isActive===false); const total=activeAccounts.reduce((s,a)=>s+Number(a.currentBalance||0),0); const summary=getPeriodSummary(transactions)
 const renderAccount=(account)=>{const accountTransactions=transactions.filter(t=>(t.account||t.accountName||'').includes(account.name));const accountIncome=accountTransactions.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount||0),0);const accountExpense=accountTransactions.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount||0),0);return <article className={`account-detail-card card ${account.isActive===false?'account-inactive':''}`} key={account.id}><AccountCard account={account}/><div className="account-detail-stats"><span>Pemasukan<strong>{formatCurrency(accountIncome)}</strong></span><span>Pengeluaran<strong>{formatCurrency(accountExpense)}</strong></span></div><div className="account-card-actions">{account.isActive===false?<button onClick={()=>toggleAccountActive(account.id,true)}><RotateCcw/>Aktifkan kembali</button>:<><button onClick={()=>setReconcile(account)}><Scale/>Rekonsiliasi</button><button className="deactivate-account" onClick={()=>setDeactivating(account)}><Archive/>Nonaktifkan</button></>}<button>Riwayat <ArrowRight/></button></div></article>}
 return <><PageTitle eyebrow="AKUN & DOMPET" title="Semua akun" subtitle="Pantau saldo dan aktivitas di setiap tempat uangmu tersimpan." action={<button className="primary-btn" onClick={()=>setOpen(true)}><Plus/>Tambah akun</button>}/>
 <section className="account-overview card"><div><span>Total saldo aktif</span><strong>{formatCurrency(total)}</strong><small>{activeAccounts.length} akun aktif</small></div><div className="account-overview-stat"><i className="income"><ArrowDownLeft/></i><span>Pemasukan bulan ini<strong>{formatCurrency(summary.income)}</strong></span></div><div className="account-overview-stat"><i className="expense"><ArrowUpRight/></i><span>Pengeluaran bulan ini<strong>{formatCurrency(summary.expense)}</strong></span></div></section>
 {activeAccounts.length?<div className="accounts-page-grid">{activeAccounts.map(renderAccount)}</div>:<div className="card empty-state"><Scale/><h3>Belum ada akun aktif</h3><p>Tambahkan akun baru atau aktifkan kembali akun lama.</p></div>}
 {inactiveAccounts.length>0&&<section className="inactive-accounts"><div className="section-head"><div><h2>Akun nonaktif</h2><p>Tidak masuk saldo aktif dan tidak dapat dipakai untuk transaksi baru.</p></div></div><div className="accounts-page-grid">{inactiveAccounts.map(renderAccount)}</div></section>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Tambah akun" description="Tidak perlu logo—pilih warna untuk mengenali akunmu."><AccountForm onDone={()=>setOpen(false)}/></Modal>
 <Modal open={!!reconcile} onClose={()=>setReconcile(null)} title={`Rekonsiliasi ${reconcile?.name||''}`} description="Samakan saldo aplikasi dengan saldo nyata."><form className="finance-form" onSubmit={(e)=>{e.preventDefault();notify('Transaksi penyesuaian berhasil dibuat');setReconcile(null)}}><div className="reconcile-box"><span>Saldo aplikasi<strong>{formatCurrency(reconcile?.currentBalance)}</strong></span><label>Saldo nyata<input type="number" defaultValue={reconcile?.currentBalance}/></label></div><p className="form-note">Selisih akan dicatat sebagai transaksi penyesuaian saldo, bukan pemasukan biasa.</p><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setReconcile(null)}>Batal</button><button className="primary-btn">Buat penyesuaian</button></div></form></Modal>
 <Modal open={!!deactivating} onClose={()=>setDeactivating(null)} title={`Nonaktifkan ${deactivating?.name||''}?`} description="Riwayat transaksi tetap tersimpan dan akun dapat diaktifkan kembali."><div className="confirm-account-action"><p>Akun ini tidak akan dihitung dalam total saldo dan tidak muncul saat membuat transaksi baru.</p><div className="form-actions"><button className="secondary-btn" onClick={()=>setDeactivating(null)}>Batal</button><button className="danger-btn" onClick={async()=>{await toggleAccountActive(deactivating.id,false);setDeactivating(null)}}><Archive/>Nonaktifkan akun</button></div></div></Modal></>
}
