import { useState } from 'react'
import { Bell, Check, ChevronRight, Database, Download, KeyRound, LogOut, Moon, Palette, Shield, Sun, Tag, UserRound, WalletCards } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import PageTitle from '../../components/common/PageTitle'
import { useAuth } from '../../context/AuthContext'
import { useFinance } from '../../context/FinanceContext'
import { useTheme } from '../../context/ThemeContext'

export default function SettingsPage(){const[section,setSection]=useState('profil');const{theme,setTheme,hiddenAmounts,setHiddenAmounts}=useTheme();const{accounts,transactions,budgets,notify}=useFinance();const{user,logout}=useAuth();const navigate=useNavigate();const exportJson=()=>{const blob=new Blob([JSON.stringify({accounts,transactions,budgets},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='financemy-backup.json';a.click();URL.revokeObjectURL(url);notify('Data berhasil diekspor')};const doLogout=async()=>{await logout();navigate('/login')};const menu=[['profil','Profil',UserRound],['preferensi','Preferensi',Palette],['kategori','Kategori & tag',Tag],['data','Data',Database],['keamanan','Keamanan',Shield]];return <><PageTitle eyebrow="PERSONALISASI" title="Pengaturan" subtitle="Atur FinanceMy sesuai cara kamu mengelola keuangan."/><div className="settings-layout"><aside className="settings-menu card">{menu.map(([id,label,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><Icon/>{label}<ChevronRight/></button>)}</aside><section className="settings-panel card">{section==='profil'&&<><header><h2>Profil</h2><p>Informasi dasar akunmu. FinanceMy tidak menggunakan foto profil.</p></header><form className="finance-form settings-form" onSubmit={e=>{e.preventDefault();notify('Profil berhasil diperbarui')}}><label>Nama lengkap<input defaultValue={user?.displayName||user?.email?.split('@')[0]||''}/></label><label>Email<input value={user?.email||''} readOnly/></label><div className="form-grid"><label>Mata uang<select><option>IDR — Rupiah</option></select></label><label>Format tanggal<select><option>4 Agustus 2026</option><option>04/08/2026</option></select></label></div><div className="form-actions"><button className="primary-btn">Simpan perubahan</button></div></form></>}
{section==='preferensi'&&<><header><h2>Preferensi</h2><p>Tampilan, privasi nominal, dan pengingat.</p></header><div className="theme-options"><button className={theme==='light'?'active':''} onClick={()=>setTheme('light')}><Sun/><span>Mode terang<small>Latar cerah dan bersih</small></span>{theme==='light'&&<Check/>}</button><button className={theme==='dark'?'active':''} onClick={()=>setTheme('dark')}><Moon/><span>Mode gelap<small>Lebih nyaman saat malam</small></span>{theme==='dark'&&<Check/>}</button></div><div className="setting-rows"><Toggle icon={WalletCards} title="Sembunyikan nominal" note="Samarkan semua angka saldo dan ringkasan" checked={hiddenAmounts} onChange={setHiddenAmounts}/><Toggle icon={Bell} title="Pengingat tagihan" note="Ingatkan 3 hari sebelum jatuh tempo" checked={true}/></div></>}
{section==='kategori'&&<><header><h2>Kategori & tag</h2><p>Kategori bawaan dapat dinonaktifkan, tetapi tidak dihapus permanen.</p></header><div className="category-settings">{['Makan & Minum','Transportasi','Belanja','Kebutuhan Rumah','Tagihan','Langganan','Hiburan'].map((name,i)=><div key={name}><i style={{background:['#087f5b','#2271b3','#8b5cf6','#e08a17'][i%4]}}/><span><strong>{name}</strong><small>{i%3+3} subkategori</small></span><input type="checkbox" defaultChecked aria-label={`Aktifkan ${name}`}/></div>)}</div></>}
{section==='data'&&<><header><h2>Data</h2><p>Unduh salinan data yang dibuat FinanceMy. Tidak ada upload file.</p></header><div className="data-actions"><button onClick={exportJson}><span><Database/><strong>Export semua data<small>Format JSON untuk arsip pribadi</small></strong></span><Download/></button><button onClick={()=>notify('CSV transaksi berhasil dibuat')}><span><Database/><strong>Export transaksi<small>Format CSV untuk spreadsheet</small></strong></span><Download/></button></div><div className="danger-zone"><strong>Zona berisiko</strong><p>Penghapusan data bersifat permanen dan memerlukan konfirmasi ulang.</p><button>Hapus seluruh transaksi</button></div></>}
{section==='keamanan'&&<><header><h2>Keamanan</h2><p>Kelola password dan sesi akun.</p></header><div className="security-actions"><button><KeyRound/><span><strong>Ubah password</strong><small>Kirim tautan aman melalui email</small></span><ChevronRight/></button><button onClick={doLogout}><LogOut/><span><strong>Keluar dari akun</strong><small>Akhiri sesi di perangkat ini</small></span><ChevronRight/></button></div></>}</section></div></>}

function Toggle({icon:Icon,title,note,checked,onChange=()=>{}}){return <label className="toggle-row"><Icon/><span><strong>{title}</strong><small>{note}</small></span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i/></label>}
