import { useState } from 'react'
import { CalendarClock, Check, ChevronRight, Clock3, Plus, Repeat2, Tv2, Wifi, Zap } from 'lucide-react'
import Modal from '../../components/common/Modal'
import PageTitle from '../../components/common/PageTitle'
import { useFinance } from '../../context/FinanceContext'
import { formatCurrency } from '../../utils/formatters'

const items=[
 {id:1,name:'WiFi rumah',type:'Tagihan',amount:350000,next:'8 Agu 2026',frequency:'Bulanan',account:'BSI',icon:Wifi,color:'#2271b3'},
 {id:2,name:'Netflix',type:'Langganan',amount:186000,next:'12 Agu 2026',frequency:'Bulanan',account:'Blu',icon:Tv2,color:'#e05252'},
 {id:3,name:'Listrik',type:'Tagihan',amount:425000,next:'15 Agu 2026',frequency:'Bulanan',account:'BSI',icon:Zap,color:'#e08a17'},
]
export default function RecurringPage(){const [tab,setTab]=useState('rutin');const [open,setOpen]=useState(false);const [pending,setPending]=useState([1]);const {notify}=useFinance();const confirm=(id)=>{setPending(pending.filter(x=>x!==id));notify('Pembayaran dikonfirmasi dan transaksi dibuat')};return <><PageTitle eyebrow="OTOMATISASI RINGAN" title="Transaksi rutin" subtitle="Tagihan, langganan, dan transaksi berulang dalam satu tempat." action={<button className="primary-btn" onClick={()=>setOpen(true)}><Plus/>Tambah rutin</button>}/><div className="page-tabs"><button className={tab==='rutin'?'active':''} onClick={()=>setTab('rutin')}>Semua rutin</button><button className={tab==='tagihan'?'active':''} onClick={()=>setTab('tagihan')}>Tagihan</button><button className={tab==='langganan'?'active':''} onClick={()=>setTab('langganan')}>Langganan</button><button className={tab==='kalender'?'active':''} onClick={()=>setTab('kalender')}>Kalender</button></div>
 {pending.length>0&&<div className="pending-banner"><Clock3/><div><strong>1 transaksi menunggu konfirmasi</strong><p>WiFi rumah telah jatuh tempo. Konfirmasi untuk mencatat pengeluaran.</p></div><button className="primary-btn" onClick={()=>confirm(1)}><Check/>Konfirmasi bayar</button></div>}
 <section className="recurring-summary"><article><Repeat2/><span>Biaya rutin bulanan<strong>{formatCurrency(961000)}</strong></span></article><article><CalendarClock/><span>Jatuh tempo 14 hari<strong>3 transaksi</strong></span></article><article><Tv2/><span>Langganan aktif<strong>Rp2.232.000/tahun</strong></span></article></section>
 <section className="card recurring-list"><header><strong>Jadwal mendatang</strong><span>Urut berdasarkan tanggal terdekat</span></header>{items.filter(i=>tab==='rutin'||tab==='kalender'||i.type.toLowerCase()===tab).map(Item=><div key={Item.id}><i style={{background:`${Item.color}18`,color:Item.color}}><Item.icon/></i><span><strong>{Item.name}</strong><small>{Item.type} • {Item.frequency}</small></span><span><small>Jatuh tempo</small><strong>{Item.next}</strong></span><span><small>Akun</small><strong>{Item.account}</strong></span><b>{formatCurrency(Item.amount)}</b><button className="icon-btn"><ChevronRight/></button></div>)}</section>
 <Modal open={open} onClose={()=>setOpen(false)} title="Tambah transaksi rutin" description="Pemeriksaan jatuh tempo dilakukan setiap aplikasi dibuka."><form className="finance-form" onSubmit={e=>{e.preventDefault();notify('Transaksi rutin berhasil dibuat');setOpen(false)}}><div className="form-grid"><label>Nama<input required placeholder="Contoh: Spotify"/></label><label>Jenis<select><option>Langganan</option><option>Tagihan</option><option>Cicilan</option><option>Pemasukan rutin</option></select></label><label>Nominal<input required type="number" min="1"/></label><label>Frekuensi<select><option>Bulanan</option><option>Mingguan</option><option>Tahunan</option></select></label><label>Tanggal berikutnya<input type="date" required/></label><label>Metode pencatatan<select><option>Minta konfirmasi</option><option>Pengingat saja</option><option>Catat otomatis saat aplikasi dibuka</option></select></label></div><p className="form-note">Occurrence key unik mencegah transaksi dibuat dua kali untuk periode yang sama.</p><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Batal</button><button className="primary-btn">Simpan transaksi rutin</button></div></form></Modal></>}
