import { useState } from 'react'
import { CalendarDays, Home, Laptop, Plus, ShieldCheck, Sparkles } from 'lucide-react'
import Modal from '../../components/common/Modal'
import PageTitle from '../../components/common/PageTitle'
import ProgressBar from '../../components/common/ProgressBar'
import { useFinance } from '../../context/FinanceContext'
import { formatCurrency } from '../../utils/formatters'

const goals=[{name:'Dana darurat',icon:ShieldCheck,target:30000000,saved:12600000,deadline:'Des 2027',color:'#087f5b',priority:'Prioritas tinggi'},{name:'Laptop kerja',icon:Laptop,target:18000000,saved:9900000,deadline:'Feb 2027',color:'#2271b3',priority:'Prioritas sedang'},{name:'Uang muka rumah',icon:Home,target:150000000,saved:32500000,deadline:'Agu 2030',color:'#8b5cf6',priority:'Jangka panjang'}]
export default function GoalsPage(){const[open,setOpen]=useState(false);const{notify}=useFinance();return <><PageTitle eyebrow="MASA DEPAN" title="Target keuangan" subtitle="Ubah rencana besar menjadi langkah kecil yang terukur." action={<button className="primary-btn" onClick={()=>setOpen(true)}><Plus/>Tambah target</button>}/><section className="goal-highlight"><div><span><Sparkles/>PROGRESS KESELURUHAN</span><h2>Kamu sudah mengumpulkan <em>Rp55 juta</em></h2><p>dari total target Rp198 juta di 3 tujuan aktif.</p></div><div className="goal-ring"><strong>28%</strong><span>tercapai</span></div></section><div className="goals-grid">{goals.map(item=><article className="card goal-card" key={item.name}><header><i style={{background:`${item.color}18`,color:item.color}}><item.icon/></i><span><strong>{item.name}</strong><small>{item.priority}</small></span><em>Aktif</em></header><div className="goal-value"><span>Terkumpul<strong>{formatCurrency(item.saved)}</strong></span><span>Target<strong>{formatCurrency(item.target)}</strong></span></div><ProgressBar value={item.saved/item.target*100} color={item.color}/><div className="goal-foot"><span><CalendarDays/> {item.deadline}</span><strong>Saran {formatCurrency((item.target-item.saved)/18)}/bulan</strong></div></article>)}</div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Buat target keuangan" description="Kontribusi dicatat sebagai alokasi atau transfer, bukan pengeluaran."><form className="finance-form" onSubmit={e=>{e.preventDefault();notify('Target keuangan berhasil dibuat');setOpen(false)}}><div className="form-grid"><label>Nama target<input required placeholder="Contoh: Dana pendidikan"/></label><label>Nominal target<input required type="number" min="1"/></label><label>Dana saat ini<input type="number" min="0"/></label><label>Deadline<input type="date" required/></label><label>Prioritas<select><option>Tinggi</option><option>Sedang</option><option>Rendah</option></select></label><label>Akun tujuan<select><option>Blu</option><option>BSI</option></select></label></div><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Batal</button><button className="primary-btn">Simpan target</button></div></form></Modal></>}
