import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CalendarDays, ChevronDown, Download, Info, TrendingDown, TrendingUp } from 'lucide-react'
import PageTitle from '../../components/common/PageTitle'
import ProgressBar from '../../components/common/ProgressBar'
import { cashFlowData, categoryData } from '../../constants/demoData'
import { formatCurrency } from '../../utils/formatters'

export default function ReportsPage(){return <><PageTitle eyebrow="ANALISIS KEUANGAN" title="Laporan" subtitle="Lihat pola, bandingkan periode, dan pahami kebiasaanmu." action={<div className="page-actions"><button className="period-select"><CalendarDays/>6 bulan terakhir<ChevronDown/></button><button className="secondary-btn"><Download/>Ekspor</button></div>}/><section className="report-metrics"><article><span>Total pemasukan</span><strong>Rp36.600.000</strong><p className="positive"><TrendingUp/> 6,4% dari periode lalu</p></article><article><span>Total pengeluaran</span><strong>Rp25.100.000</strong><p className="positive"><TrendingDown/> 3,2% lebih rendah</p></article><article><span>Total tersimpan</span><strong>Rp11.500.000</strong><p className="positive"><TrendingUp/> Rasio tabungan 31,4%</p></article><article><span>Rata-rata harian</span><strong>Rp137.200</strong><p><Info/> Berdasarkan 183 hari</p></article></section>
<div className="reports-grid"><article className="card report-wide"><div className="section-head"><div><h2>Pemasukan vs pengeluaran</h2><p>Dalam ribuan Rupiah</p></div></div><ResponsiveContainer width="100%" height={300}><BarChart data={cashFlowData}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="income" name="Pemasukan" fill="#099268" radius={[5,5,0,0]}/><Bar dataKey="expense" name="Pengeluaran" fill="#e05252" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></article><article className="card"><div className="section-head"><div><h2>Pengeluaran per kategori</h2><p>Agustus 2026</p></div></div><ResponsiveContainer width="100%" height={215}><PieChart><Pie data={categoryData} dataKey="value" innerRadius={55} outerRadius={82}>{categoryData.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip formatter={v=>formatCurrency(v)}/></PieChart></ResponsiveContainer><div className="category-legend report">{categoryData.map(item=><span key={item.name}><i style={{background:item.color}}/>{item.name}<strong>{formatCurrency(item.value)}</strong></span>)}</div></article><article className="card report-wide"><div className="section-head"><div><h2>Perubahan saldo</h2><p>Saldo bersih akhir bulan</p></div></div><ResponsiveContainer width="100%" height={250}><LineChart data={cashFlowData}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Line type="monotone" dataKey="balance" name="Saldo" stroke="#2271b3" strokeWidth={3} dot={{fill:'#2271b3',r:4}}/></LineChart></ResponsiveContainer></article><article className="card health-card"><div className="section-head"><div><h2>Kesehatan keuangan</h2><p>Komponen transparan, bukan skor misterius</p></div><em>Baik</em></div><div className="health-list"><span>Rasio tabungan<strong>31,4%</strong><ProgressBar value={78}/></span><span>Pengeluaran / pemasukan<strong>68,6%</strong><ProgressBar value={69} color="#2271b3"/></span><span>Dana darurat<strong>2,5 bulan</strong><ProgressBar value={42} color="#e08a17"/></span><span>Tagihan terlambat<strong>0</strong><ProgressBar value={100}/></span></div><p><Info/>Ringkasan ini bukan penilaian finansial profesional.</p></article></div></>}
